### ISSUE TITLE
String: getter for char* to the value

### ISSUE THREAD

**Issue by yth** [MHebes/cs4500-a1-part2#14]
Please create specifications of a getter for the char* wrapped by the String class. Otherwise, we cannot use the value protected by the class.

**Comment by gyroknight** [comment]
Please open an issue [here](https://github.com/chasebish/cwc_object_string).

**Comment by gyroknight** [comment]
Is there any specific reason you need access to the raw value @yth? Providing the raw data is potentially dangerous.

**Comment by yth** [comment]
I thought I needed it to create another copy of the String. On reflection, maybe a clone method is the better way to go.
