### ISSUE TITLE
List constructor: requires no allocation at creation

### ISSUE THREAD

**Issue by yth** [MHebes/cs4500-a1-part2#15]
Map is required to return List objects when asked about its keys and values. This brings List within the scope of map specification.

According to the comment, it is required to not allocate any additional memory for potential list contents. It also requires the size of the list to be 1.

This seems mutually incompatible. Please change the initial List size to 0, or allow the allocation of some memory at construction.

**Comment by MHebes** [comment]
Oh that's my bad, didn't change comments after removing implementations.
The "vector with size 1" referred to the initial memory allocation the list object would do - I'll make that change.
