### ISSUE TITLE
Implementation already exists

### ISSUE THREAD

**Issue by MHebes** [MHebes/cs4500-a1-part2#2]
For string.h and list.h we included our implementations from previous assignments. These should be removed. Doing this now, stand by.

**Comment by MHebes** [comment]
Also if we're agreeing on a class-common implementation for object.h/string.h we should talk about that

**Comment by gyroknight** [comment]
Old implementation needs to be purged from history, I can look into clearing that.

**Comment by MHebes** [comment]
Ugh. Okay, just squash and force push to master? I'll let you do that if you want

**Comment by MHebes** [comment]
@gyroknight can you also move everything into the part2/ folder? Don't know how it escaped.

**Comment by gyroknight** [comment]
Repo should be clean now.
