### ISSUE TITLE
Use Array instead of list

### ISSUE THREAD

**Issue by MHebes** [MHebes/cs4500-a1-part2#21]
Hey all - wanted to ask your opinions on the spec.

Map.keys() and Map.values( ) return a List object - but List is just an alias for Array.

Since you're implementing Array, I don't see any reason you need to implement List as well.

I want to change those methods to return your Array instead of my List, but I don't know what the best way to do that is. Thoughts?

**Comment by MHebes** [comment]
Another option of course would be to just have list.h be a wrapper for array.h, which I'm sure you're already doing :)

**Comment by yth** [comment]
I think it depends on what you want to do with your map. Based on the design, I think what you had in mind was to use a linear search to find the key, its index and use the key's index to find the value associated with it. Is this correct?

**Comment by gyroknight** [comment]
The purpose of `Map.keys()` and `Map.values()` are to provide an iterable list of parts of the map for use in loops.

**Comment by MHebes** [comment]
I did not imagine that keys() and values() would necessarily be used in the internal implementation, no. They are methods designed to be useful for whoever is using this map.

They just give lists for whatever purpose whoever asked for them needs.

See java's [HashMap.keySet](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#keySet--) and [values](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#values--) methods for an analogy of what they would do.

**Comment by yth** [comment]
In that case, I think you essentially just need a container that knows its size and impose some sort of ordering on the items. Lists and arrays are both overkills.

**Comment by MHebes** [comment]
> you essentially just need a container that knows its size and impose some sort of ordering on the items

That's what a list or array is :)

I'm just asking which one you want it to return - _our_ custom **List** class, or the **Array** class that _you_ are already implementing?

**Comment by yth** [comment]
I meant we didn't need so many methods attached to either. We can achieve the same goal with fewer methods.

**Comment by MHebes** [comment]
I'm going to keep the spec as returning a List.

I expect List to only be a very thin wrapper around your Array implementation (from the other repos). It should take five minutes to implement after you've implemented your Array. 

If I knew what your implementation's interface was and could coordinate it with all the other teams, I would use it directly instead of requiring this wrapper interface.

**Comment by MHebes** [comment]
I am sympathetic to your situation - in your List implementation, just add a member variable called _array and make it point to an instance of your Array class. Each of the methods can now pretty much be one-liners that call methods on that array.
e.g.

if your Array had a method `void push(Object* obj)`, you could implement the list `push_back` method by doing this:

```cpp
class List : public Object {
public:
    Array* array_;

    List() : array_(new Array()) {}

    ...

    // Adds an element to the end of the list
    virtual void push_back(Object* str) {
        array_->push(str);
    }

    ...
}
```

**Comment by MHebes** [comment]
@yth I've thought about this some more and I think you're right. Ideally I would return the Array class, but since I don't know what methods that has, I can't test it.

I will remove all methods except `size`, `get`, `index_of`, and whatever it inherits from Object.

**Comment by yth** [comment]
Thanks!
