### ISSUE TITLE
Test File: test_clone not fully deleting everything allocated

### ISSUE THREAD

**Issue by yth** [MHebes/cs4500-a1-part2#22]
Please add delete map1 to the test function. It's segfaulting.

**Comment by MHebes** [comment]
You are correct that it's not deleting everything, and I'll fix that - but that would not be the cause of the segfault, it would just cause leaked memory

**Comment by MHebes** [comment]
map1 doesn't need to be deleted, as it's allocated on the stack and is deleted automatically when the function returns.
However, the keys and vals lists do, which is what I'm fixing.
