### ISSUE TITLE
Get keys and values: eliminate methods?

### ISSUE THREAD

**Issue by yth** [MHebes/cs4500-a1-part2#24]
It seems a bad idea to have these two methods when we potentially could be putting millions of key-value pairs into the map.

We will be doing a lot of copying for little value since we usually just want to find out if a key is among the keys in the map, or if a value is among the values.

**Comment by MHebes** [comment]
It's up to the user if they want to call this method, but it should be in the spec.
Note though that we said: "a copy **of the list** of keys", not a list of copies of keys :)

Also please give your feedback on #21 if you want to make your life easier.

**Comment by MHebes** [comment]
I am sympathetic to your situation - in your List implementation, just add a member variable called _array and make it point to an instance of your Array class. Each of the methods can now pretty much be one-liners that call methods on that array.
e.g.

if your Array had a method `void push(Object* obj)`, you could implement the list `push_back` method by doing this:

```cpp
class List : public Object {
public:
    Array* array_;

    List() : array_(new Array()) {}

    ...

    // Adds an element to the end of the list
    virtual void push_back(Object* str) {
        array_->push(str);
    }

    ...
}
```
