### ISSUE TITLE
Adding Object methods back to List

### ISSUE THREAD

**Issue by ricardolarios** [MHebes/cs4500-a1-part2#26]
We saw that you removed the methods that List inherits from the Object class (i.e. `equals` and `hash`) so could you just add those back, since those should be stubs in any class that inherits from Object?

**Comment by MHebes** [comment]
They are part of the interface because of the inheritance - if you want to implement them in a child class I believe that’s up to you. Me adding stubs wouldn’t change the interface

**Comment by gyroknight** [comment]
By adding `equals` and `hash` to the `List` interface, we would be stating that `List` must override those methods, not just that it has those methods. Those methods are implicitly inherited from `Object`; it is up to your implementation to decide whether or not you want to override them.
