### ISSUE TITLE
Fix incorrect test assertions

### ISSUE THREAD

**Issue by bdourdoufis** [MHebes/cs4500-a1-part2#29]
There are a few assertions currently in your test file that won't pass.

On line 341: the size of map1 should be equal to 2, not 3, since the third put call is replacing the pairing of 'c' to 'd' with 'c' to 'a', not adding a new entry.

On line 368: the same issue as on line 341.

On lines 373 and 374: the keys and values lists for the map should both be of size 2 because the map itself only has two entries.

**Comment by gyroknight** [comment]
Fixed.
