### ISSUE TITLE
Design and ownership of key and value lists

### ISSUE THREAD

**Issue by yth** [MHebes/cs4500-a1-part2#30]
Based on the tests, it seems that the only thing that maps can own is the key and value lists. I think that's too forceful a decision to make.

The reason that I say key and value lists are the only things that can be owned by the map is that the deletes in the clone test are only freeing those two lists for map1. Other heap memory used by the map is not freed.

If a map can only own two lists, it'll be too vulnerable to the result of hash collisions, and/or not get the expected performance.

The simple fix is to simply change all map declaration to map pointer declarations in the test file. Calling delete on the pointers will free all the heap memory used by the map.

**Comment by gyroknight** [comment]
I'm not sure I understand what the issue is. What do you mean by "the clone test are only freeing those two lists for map1. Other heap memory used by the map is not freed"? What does "other heap memory" refer to here?

**Comment by yth** [comment]
For my particular use case, I am using a number of hash buckets to store the key-value pairs. Each hash bucket is a region of memory on the heap. Other people might be using different designs. And, they might also need heap memory.

In the second test, you have map1. You get two pointers to keys list and values list. Instead of delete map1, you rely on the fact that everything besides those two lists are things on the stack.

**Comment by gyroknight** [comment]
The destructor gets called whenever an object goes out of scope in C++. Calling `delete` is not a requirement to destroy the object. If you use heap memory in your implementation, it's up to you to clean it up in the destructor.

**Comment by yth** [comment]
Cool! I did not know that about C++.
