### ISSUE TITLE
Map's clone method: design does not match test

### ISSUE THREAD

**Issue by yth** [MHebes/cs4500-a1-part2#4]
According to the design, the clone method makes a shallow copy and does not copy keys and values. However, the test implies that the clone method also clones keys and values. Please clarify.

**Comment by MHebes** [comment]
It should be a shallow copy. I can update the test, but the test will pass either way.

**Comment by yth** [comment]
Does the clone method give the new map the hash of the original map?

**Comment by gyroknight** [comment]
Yes.

**Comment by yth** [comment]
Thanks for clarifying!

**Comment by gyroknight** [comment]
Do we still want to refine this test or leave it as-is @MHebes?

**Comment by MHebes** [comment]
@gyroknight We can refine it, sure. Assigning to myself

**Comment by yth** [comment]
test_clone still seems to assume clone() make a full copy and not a shallow copy.

Just to make sure we have the same understanding of what a shallow copy is, I assumed shallow copy means give the copy will have the same hash as the original. It'll have as many slots to potentially put key-value pairs as the original. However, none of the keys/values from the original is in the new map.

**Comment by gyroknight** [comment]
A shallow copy means that the keys and values are the same, down to the memory address.

**Comment by yth** [comment]
Understood!
