### ISSUE TITLE
Map hash method: what happens to the hash after removing an key-value pair

### ISSUE THREAD

**Issue by yth** [MHebes/cs4500-a1-part2#5]
Please create tests or description to specify what should be expected when we remove a key-value pair.

**Comment by gyroknight** [comment]
Removing a pair will invalidate the hash of the map.

**Comment by yth** [comment]
Thanks!

**Comment by gyroknight** [comment]
Reopening until documentation gets updated.

**Comment by MHebes** [comment]
Closing because I believe this is an implementation detail. The simplest valid hash function is just { return 0; }.
